export const ErrorCodes = Object.freeze({
    UI_ERR_COMPONENT_NOT_FOUND: 'UI_ERR_COMPONENT_NOT_FOUND',
    UI_ERR_UNSUPPORTED_COMPONENT_ACTION: 'UI_ERR_UNSUPPORTED_COMPONENT_ACTION',
    UI_ERR_INVALID_INPUT: 'UI_ERR_INVALID_INPUT',

    APP_ERR_ACTION_FAILED: 'APP_ERR_ACTION_FAILED',
    APP_ERR_INVALID_ACTION_RESULT: 'APP_ERR_INVALID_ACTION_RESULT',
    APP_ERR_UNEXPECTED_STATE: 'APP_ERR_UNEXPECTED_STATE',

    TOPO_ERR_INVALID_CONNECTION: 'TOPO_ERR_INVALID_CONNECTION',
    TOPO_ERR_NODE_REBUILD_FAILED: 'TOPO_ERR_NODE_REBUILD_FAILED',

    SIM_ERR_SOLVER_FAILED: 'SIM_ERR_SOLVER_FAILED',
    SIM_ERR_NUMERICAL_INSTABILITY: 'SIM_ERR_NUMERICAL_INSTABILITY',

    IO_ERR_READ_FAILED: 'IO_ERR_READ_FAILED',
    IO_ERR_WRITE_FAILED: 'IO_ERR_WRITE_FAILED'
});
